### ISSUE TITLE
433 interference issue

### ISSUE THREAD

**Issue by kovi44** [StryKaizer/NodeMCU-Somfy#2]
Hi,

I really love your piece of code. I used for my project. However what I found is that as soon as the esp is powered then it cause a 433MHz interference and all my 433,95MHz device stop to operate correctly. If I unplug it then everything back to normal operation.

I was thinking that my hardware is built incorrectly so I built several different piece of hw using different esp8266 and also different 433 transmitter using RF433,42MHz (which I bought using aliexpress and ebay - different sources). For each setup same result.

Have you any idea what's wrong? My guess is the nodemcu module implementation, but not sure.

Thanks for your response
Ciao
Lukas

**Comment by mschaeuble** [comment]
I had the same issue first when my transmitter was not connected to the correct pin on my ESP8266.

**Comment by kovi44** [comment]
> I had the same issue first when my transmitter was not connected to the correct pin on my ESP8266.

And my ask to help me.
I'm using Wemos D1 esp and transmitter is connected to D4 for data, 5V as VCC and GND to GND. (using different setup I also tried D3)

If D4 was used then pin in settings.lua got value 4 (pin = 4), if D3 then pin =3 (based on https://escapequotes.net/esp8266-wemos-d1-mini-pins-and-diagram/ )

where did I made a mistake?
Thanks for support

**Comment by mschaeuble** [comment]
In my case, I'm using a D1 mini (china clone) using pinout D1 for data and pin = 1 in the settings.lua.

**Comment by kovi44** [comment]
> In my case, I'm using a D1 mini (china clone) using pinout D1 for data and pin = 1 in the settings.lua.

tomorrow, will try to connect it the same way and will update you, if it helps. thanks, really appriciate your support

**Comment by StryKaizer** [comment]
@kovi44 yes, I had that same issue myself in another project a while ago, which also turned out the transmitter was not correctly connected (wrong pin). My other 433 devices did not like it either ;), so check your pinout
